# Generated by Django 5.1.6 on 2025-03-18 18:44

import localflavor.br.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='cnpj',
            field=localflavor.br.models.BRCNPJField(max_length=18, unique=True),
        ),
    ]
