# Generated by Django 5.1.6 on 2025-04-02 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('PATH', models.FileField(max_length=255, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('titulo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('OBRIGATORIO', 'Obrigatório'), ('COMERCIO', 'Comércio'), ('SERVICO', 'Serviço'), ('INDUSTRIA', 'Indústria')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaSecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_final', models.IntegerField(default=0)),
                ('data_resposta', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.secao')),
            ],
            options={
                'verbose_name_plural': 'Respostas das Seções',
                'unique_together': {('usuario', 'secao')},
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('explicacao', models.TextField(blank=True)),
                ('ordemPerguntas', models.JSONField(default=list)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='questionario.secao')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.pergunta')),
                ('resposta_secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.respostasecao')),
            ],
            options={
                'verbose_name_plural': 'Respostas das Perguntas',
                'unique_together': {('resposta_secao', 'pergunta')},
            },
        ),
    ]
