# Generated by Django 5.1.6 on 2025-04-11 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensao',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensoes', to='questionario.modulo'),
        ),
        migrations.CreateModel(
            name='RespostaModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorFinal', models.IntegerField(default=0)),
                ('dataResposta', models.DateTimeField(auto_now=True)),
                ('modulo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Respostas dos Módulos',
                'unique_together': {('usuario', 'modulo')},
            },
        ),
        migrations.DeleteModel(
            name='RespostaPergunta',
        ),
    ]
