# Generated by Django 5.1.6 on 2025-04-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['secao', 'id_secao']},
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='ordemPerguntas',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='id_secao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secao',
            name='ordemPerguntas',
            field=models.JSONField(default=list),
        ),
    ]
